language: python
sudo: false
addons:
  postgresql: 9.6
python:
- 3.6
- 3.7-dev
install:
- pip install -U pip setuptools
- pip install pytest-runner
before_script:
- psql -c 'create database test;' -U postgres
script:
- python setup.py test
before_deploy:
- echo "__version__ = '$(git describe --tags)'" > aioworkers_pg/version.py
deploy:
  provider: pypi
  user: abogushov
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  skip_cleanup: true
  password:
    secure: dOZzs/kHK1nudkTFmcP43AFY9sWDreESUBttrTe735G8R8hMuHFLuoqwMW2wOfzd7Sn4uxlv4wADnctb2xUiDY4GDNzNCUhlxGANDwklPl1ogMhhZkKvWFecU81WigcTM3PMxhyr+9K3yuUVphDMcw02TWFk1MHcDs2PZIaw3VyzfqZc00QhkMcTi4gl67Pv4KRlXnZp/wttS8mmWhiJqBVE/Fi7FkD4ZuXQbPWclT7Vs4MNf1aqtMmYRYZ+u8aoXVFfF1kqGjpsyR0uT6s51hbeD/KQ/h4y1TISyIONP7gfc2aV4+6xdScDMmBpl0CslaM+t5KsdQcOwDd1sJp2nrAdQLOrIscmwPAosFr33lx0OBYcZB4hmYf/Xx94BDUXPNBip3xZc9X27jq0YSVuofs7jU0xe5liqtXpMd6jO4Y5NzndT1QZTutqakWpxgqmF4SiaRXWmA+J+BD6VLVFWO9dZsGrHCiDjJxePqz1WQdON3CXd8HsxJQKN5s5tyOCXagivdEsW1AvRcjBTzAs7ScbfqbwKmxvCBx4LHhPmpEelrf+eKBGMhDAw9Pqw7/Um0v2MMWa7cnKzVmz6HreUg4EIwpw9QEi9LYY5b1esJENfSap+fnUf0pH8yANWA64i+oa4ocMqfLNo/puZv+COLN8ylWWMkCfWDOBv+AzFTw=
