language: python

sudo: false

services: postgresql

python:
- 3.5
- 3.6
- 3.7

install:
- pip install pytest-runner

before_script:
  - psql -c 'create database test;' -U postgres

script:
- python setup.py test

