name: Build
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
          with:
            python-version: 3.8
      - name: Install dependencies
        run: pip install poetry poetry-dynamic-versioning
      - name: Install dependencies
        run: poetry-dynamic-versioning
      - name: Install deps
        run: poetry build && ls dist
