name: Build
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install deps
        run: poetry build
