name: CI
on: [push]

jobs:
  ci:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6] #[3.6, 3.7, 3.8]
        os: [ubuntu-18.04] #[ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install deps
        run: poetry install
      - name: Run pytest
        run: poetry run pytest
